/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AddrService } from "../addr.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AddrCreateInput } from "./AddrCreateInput";
import { AddrWhereInput } from "./AddrWhereInput";
import { AddrWhereUniqueInput } from "./AddrWhereUniqueInput";
import { AddrFindManyArgs } from "./AddrFindManyArgs";
import { AddrUpdateInput } from "./AddrUpdateInput";
import { Addr } from "./Addr";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AddrControllerBase {
  constructor(
    protected readonly service: AddrService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Addr })
  @nestAccessControl.UseRoles({
    resource: "Addr",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: AddrCreateInput): Promise<Addr> {
    return await this.service.create({
      data: {
        ...data,

        addr: data.addr
          ? {
              connect: data.addr,
            }
          : undefined,
      },
      select: {
        addr: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        district: true,
        fullname: true,
        id: true,
        tel: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Addr] })
  @ApiNestedQuery(AddrFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Addr",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Addr[]> {
    const args = plainToClass(AddrFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        addr: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        district: true,
        fullname: true,
        id: true,
        tel: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Addr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Addr",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: AddrWhereUniqueInput
  ): Promise<Addr | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        addr: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        district: true,
        fullname: true,
        id: true,
        tel: true,
        updatedAt: true,
        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Addr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Addr",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: AddrWhereUniqueInput,
    @common.Body() data: AddrUpdateInput
  ): Promise<Addr | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          addr: data.addr
            ? {
                connect: data.addr,
              }
            : undefined,
        },
        select: {
          addr: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          district: true,
          fullname: true,
          id: true,
          tel: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Addr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Addr",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: AddrWhereUniqueInput
  ): Promise<Addr | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          addr: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          district: true,
          fullname: true,
          id: true,
          tel: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/addrs")
  @ApiNestedQuery(AddrFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Addr",
    action: "read",
    possession: "any",
  })
  async findManyAddrs(
    @common.Req() request: Request,
    @common.Param() params: AddrWhereUniqueInput
  ): Promise<Addr[]> {
    const query = plainToClass(AddrFindManyArgs, request.query);
    const results = await this.service.findAddrs(params.id, {
      ...query,
      select: {
        addr: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        district: true,
        fullname: true,
        id: true,
        tel: true,
        updatedAt: true,
        userId: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/addrs")
  @nestAccessControl.UseRoles({
    resource: "Addr",
    action: "update",
    possession: "any",
  })
  async connectAddrs(
    @common.Param() params: AddrWhereUniqueInput,
    @common.Body() body: AddrWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      addrs: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/addrs")
  @nestAccessControl.UseRoles({
    resource: "Addr",
    action: "update",
    possession: "any",
  })
  async updateAddrs(
    @common.Param() params: AddrWhereUniqueInput,
    @common.Body() body: AddrWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      addrs: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/addrs")
  @nestAccessControl.UseRoles({
    resource: "Addr",
    action: "update",
    possession: "any",
  })
  async disconnectAddrs(
    @common.Param() params: AddrWhereUniqueInput,
    @common.Body() body: AddrWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      addrs: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
